chore: fix coverage tests (#9674)
Coverage has been failing for a while:
https://github.com/Unleash/unleash/actions/workflows/build_coverage.yaml
It looks related to minimatch version:
```
     TypeError: /home/runner/work/unleash/unleash/src/lib/util/isDefined.ts: minimatch is not a function
```

Removing `"minimatch": "^10.0.0",` resolution seems to fix it, but it
will likely introduce a security vulnerability error

Works on my machine results:
```shell
Test Suites: 345 passed, 345 total
Tests:       3 skipped, 3119 passed, 3122 total
Snapshots:   110 passed, 110 total
Time:        218.532 s
```