test: try fixing groups flakiness (#11566)
Noticed that groups test sometimes fails on CI - it can't create a user
because of the splash screen.

Example:
https://github.com/Unleash/unleash/actions/runs/22959306550/job/66645198349

```
 1) groups
       can add user to a group:
     CypressError: Timed out retrying after 12050ms: `cy.click()` failed because this element:

`<a class="mui-19353g" href="/admin/groups/1">...</a>`

is being covered by another element:

`<div class="MuiDialog-container MuiDialog-scrollPaper mui-ekeie0" role="presentation" tabindex="-1" style="opacity: 1; transition: opacity 225ms cubic-bezier(0.4, 0, 0.2, 1);">...</div>`

Fix this problem, or use {force: true} to disable error checking.
```
<img width="1280" height="720" alt="groups -- can add user to a group
(failed)"
src="https://github.com/user-attachments/assets/28951ec3-e59d-4a28-bf2b-00f8e05195c3"
/>



- We use electron on CI so I'm switching local testing to it as well. 
- Retry once - if it's just random flakiness it may help to just retry
the test.