fix: Fix broken OpenAPI
## What

This change removes the use of double quotes in the
'addPublicSignupTokenUser' endpoint summary. It also changes the
original summary to a description and adds a new, shorter summary.

## Why

The OpenAPI / docusaurus integration errors out (refer to [this failed
build](https://github.com/Unleash/unleash/actions/runs/3434792557/jobs/5726445104))
if the frontmatter contains invalid characters. In this case, it's
because the automatic sidebar label contains double quotes, which it
interprets as a new key having been declared:

```
Error:  Error while parsing Markdown front matter.
This can happen if you use special characters in front matter values (try using double quotes around that value).
Error:  Loading of version failed for version current
Error:  Unable to build website for locale en.
Error:  YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 12:
    description: "Create a user with the 'viewe ...
               ^
```

For some reason, I cannot reproduce this error locally. Instead, the
generation goes as expected.

---

Regarding using description instead of summary: summaries should be
very short and sweet, especially because they're also used in the
generated sidebar. Descriptions can be a bit wordier, so I added a
shorter summary for going forward.

## Generated output

This is what the old configuration would generate. Notice the
`sidedar_label` key on line 2:

```md
---
id: add-public-signup-token-user
sidebar_label: Create a user with the "viewer" root role and link them to a signup token
hide_title: true
hide_table_of_contents: true
api: {"tags":["Public signup tokens"],"operationId":"addPublicSignupTokenUser","requestBody":{"description":"createInvitedUserSchema","required":true,"content":{"application/json":{"schema":{"type":"object","additionalProperties":false,"required":["email","name","password"],"properties":{"username":{"type":"string"},"email":{"type":"string"},"name":{"type":"string"},"password":{"type":"string"}}}}}},"responses":{"200":{"description":"userSchema","content":{"application/json":{"schema":{"type":"object","additionalProperties":false,"required":["id"],"properties":{"id":{"type":"number"},"isAPI":{"type":"boolean"},"name":{"type":"string"},"email":{"type":"string"},"username":{"type":"string"},"imageUrl":{"type":"string"},"inviteLink":{"type":"string"},"loginAttempts":{"type":"number"},"emailSent":{"type":"boolean"},"rootRole":{"type":"number"},"seenAt":{"type":"string","format":"date-time","nullable":true},"createdAt":{"type":"string","format":"date-time"}}}}}},"400":{"description":"The request data does not match what we expect."},"409":{"description":"The provided resource can not be created or updated because it would conflict with the current state of the resource or with an already existing resource, respectively."}},"parameters":[{"name":"token","in":"path","required":true,"schema":{"type":"string"}}],"description":"Create a user with the \"viewer\" root role and link them to a signup token","method":"post","path":"/invite/{token}/signup","servers":[{"url":"<your-unleash-url>"}],"security":[{"apiKey":[]}],"securitySchemes":{"apiKey":{"type":"apiKey","in":"header","name":"Authorization"}},"jsonRequestBodyExample":{"username":"string","email":"string","name":"string","password":"string"},"info":{"title":"Unleash API","version":"4.17.2"},"postman":{"name":"Create a user with the \"viewer\" root role and link them to a signup token","description":{"type":"text/plain"},"url":{"path":["invite",":token","signup"],"host":["{{baseUrl}}"],"query":[],"variable":[{"disabled":false,"description":{"content":"(Required) ","type":"text/plain"},"type":"any","value":"","key":"token"}]},"header":[{"key":"Content-Type","value":"application/json"},{"key":"Accept","value":"application/json"}],"method":"POST","body":{"mode":"raw","raw":"\"\"","options":{"raw":{"language":"json"}}}}}
sidebar_class_name: "post api-method"
info_path: docs/reference/api/unleash/unleash-api
---

import ApiTabs from "@theme/ApiTabs";
import MimeTabs from "@theme/MimeTabs";
import ParamsItem from "@theme/ParamsItem";
import ResponseSamples from "@theme/ResponseSamples";
import SchemaItem from "@theme/SchemaItem"
import SchemaTabs from "@theme/SchemaTabs";
import DiscriminatorTabs from "@theme/DiscriminatorTabs";
import TabItem from "@theme/TabItem";

## Create a user with the &quot;viewer&quot; root role and link them to a signup token

Create a user with the &quot;viewer&quot; root role and link them to a signup token

<!-- And much much more! -->
```